import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback refresh-networks();
    callback connect(ssid: string);
    callback disconnect(ssid: string);
    property <bool> bluetooth: false;
    in property <string> curnet;
    in property <[string]> networks;
    in property <[string]> avail-networks;

    VerticalLayout {
        padding: 20px;
        alignment: center;
        HorizontalLayout {
            padding: 10px;
            spacing: 5px;
            alignment: center;

            Button {
                width: 100px;
                height: 30px;
                text: "Network";
                clicked => { root.bluetooth = false; }
            }

            Button {
                width: 100px;
                height: 30px;
                text: "Bluetooth";
                clicked => { root.bluetooth = true; }
            }
        }

        if !root.bluetooth : VerticalLayout {
            padding: 15px;
            spacing: 10px;

            Text {
                font-size: 20px;
                text: "Current Network";
            }

            if root.curnet != "None" : VerticalLayout {
                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: curnet;
                    }
                    Button {
                        width: 100px;
                        text: "Disconnect";
                        clicked => { root.disconnect(curnet); refresh-networks(); }
                    }
                    Button {
                        width: 75px;
                        text: "Forget";
                    }
                }
            }

            if root.curnet == "None" : VerticalLayout {
                Text {
                  font-size: 12px;
                  text: "You are not currently connected to a network";
                }
            }

            Button {
                width: 80px;
                text: "Refresh";
                clicked => { root.refresh-networks(); }
            }

            Text {
                font-size: 20px;
                text: "Other Networks";
            }
            VerticalLayout {
                for net in avail-networks :
                    HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: net;
                    }
                    Button {
                        width: 80px;
                        text: "Connect";
                        clicked => { connect(net); refresh-networks(); }
                    }
                }
            }


            Text {
                font-size: 20px;
                text: "Saved Networks";
            }
            VerticalLayout {
                for net in networks :
                    HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: net;
                    }
                    Button {
                        width: 80px;
                        text: "Forget";
                    }
                }
            }
        }

        if root.bluetooth : VerticalLayout {
             padding: 15px;
            spacing: 10px;
            Text {
                text: "Saved Devices";
            }
            HorizontalLayout {
                spacing: 10px;
                Text {
                    text: "device";
                }
                Button {
                    width: 80px;
                    text: "Forget";
                }
                Button {
                    width: 80px;
                    text: "Connect";
                }
            }
            Text {
                text: "Other Devices";
            }
            HorizontalLayout {
                spacing: 10px;
                Text {
                    text: "Device";
                }
                Button {
                    width: 80px;
                    text: "Connect";
                }
            }
            Button {
                text: "Refresh";
            }
        }
    }
}
